import { expect, test } from "@playwright/test";

test("fotos: buscar, agregar y cambiar sin alterar precio ni stock", async ({ page }) => {
  await page.goto("/admin/login");
  await page.getByLabel("Email").fill("admin@litoralmaq.com");
  await page.getByLabel("Contraseña").fill("admin123");
  await page.getByRole("button", { name: "Ingresar", exact: true }).click();
  await expect(page).toHaveURL(/\/admin$/);
  await page.getByRole("link", { name: "Fotos de productos", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Fotos de productos", exact: true })).toBeVisible();
  const containers = page.getByRole("group", { name: "Estado de fotos" });
  await expect(containers.getByRole("button")).toHaveCount(2);
  await expect(page.locator(".photo-list")).toHaveCount(0);
  await containers.getByRole("button", { name: /Productos sin foto/ }).click();
  const missing = page.getByRole("region", { name: "Productos sin foto" });
  const first = missing.locator("li").first();
  const name = await first.locator("strong").innerText();
  await first.getByRole("button", { name: /Agregar foto/ }).click();
  const dialog = page.getByRole("dialog");
  await dialog.getByLabel("Enlace de la imagen").fill("/products/catalog/3381-aa518-220plus.webp");
  await dialog.getByRole("button", { name: "Guardar foto" }).click();
  await expect(dialog).not.toBeVisible();
  await page.getByRole("searchbox", { name: "Buscar por nombre o código" }).fill(name);
  const withPhoto = page.getByRole("region", { name: "Productos con foto" });
  await expect(withPhoto).toContainText(name);
  await expect(missing).not.toBeVisible();
  await withPhoto.getByRole("button", { name: `Cambiar foto de ${name}`, exact: true }).click();
  await expect(dialog.locator(".photo-gallery-item")).toHaveCount(1);
  const image = { name: "foto.png", mimeType: "image/png", buffer: Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=", "base64") };
  await dialog.getByLabel("Subir desde archivos o galería").setInputFiles([image, { ...image, name: "detalle.png", buffer: Buffer.concat([image.buffer, Buffer.from([0])]) }]);
  await expect(dialog.locator(".photo-gallery-item")).toHaveCount(3);
  await expect(dialog.getByLabel("Subir desde archivos o galería")).toBeDisabled();
  await dialog.getByRole("button", { name: "Usar como principal" }).first().click();
  await dialog.getByRole("button", { name: "Guardar foto" }).click();
  await withPhoto.getByRole("button", { name: `Cambiar foto de ${name}`, exact: true }).click();
  await expect(dialog.locator(".photo-gallery-item")).toHaveCount(3);
  await expect(dialog.locator(".photo-gallery-item").first().locator("img")).toHaveAttribute("src", /^data:image\/png/);
  await dialog.getByRole("button", { name: "Cancelar" }).click();
  await page.reload();
  await containers.getByRole("button", { name: /Productos con foto/ }).click();
  await page.getByRole("searchbox", { name: "Buscar por nombre o código" }).fill(name);
  await expect(withPhoto).toContainText(name);
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
});
